
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: notebook.ipynb

import librosa
import numpy as np

from operator import itemgetter
from itertools import groupby

import os.path

import IPython.display as ipd

import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)